// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xtydylooshrcmhnzwnng.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh0eWR5bG9vc2hyY21obnp3bm5nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0ODMwNzMsImV4cCI6MjA3MjA1OTA3M30.s_JKiysnv8yKarb_yfW0AcSzzXBpsavzume2yWYZ6gk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});